### ISSUE TITLE
Transaction creation not working

### ISSUE THREAD

**Issue by straumat** [ketola/jlibra#54]
I retrieved the master branch (after your merged branch 'transaction-serialization') and when running `mvn verify`, the tests fails (my project test is also failing).
```
[INFO] Running dev.jlibra.SimpleTransactionIT
16:30:59.585| Balance for 0703a61585597d9b56a46a658464738dff58222b4393d32dd9899bedb58666e9 is 2999923995
16:30:59.593| Generated seed: major hole canal noise emerge meat enable neglect alcohol town govern skate soft excuse cereal room differ mouse
Transaction submitted with result: SubmitTransactionResult{admissionControlStatus=, mempoolStatus=, vmStatus=major_status: 3
, statusCase=VM_STATUS}
16:30:59.980| Balance for 37b7de33f04fefc1c038c5f520dc83a35af848b1bbe8cc04a9826e4f9ce15a60 is 0
16:31:01.087| Balance for 37b7de33f04fefc1c038c5f520dc83a35af848b1bbe8cc04a9826e4f9ce15a60 is 0
16:31:02.188| Balance for 37b7de33f04fefc1c038c5f520dc83a35af848b1bbe8cc04a9826e4f9ce15a60 is 0
16:31:04.293| Balance for 37b7de33f04fefc1c038c5f520dc83a35af848b1bbe8cc04a9826e4f9ce15a60 is 0
16:31:07.396| Balance for 37b7de33f04fefc1c038c5f520dc83a35af848b1bbe8cc04a9826e4f9ce15a60 is 0
16:31:12.499| Balance for 37b7de33f04fefc1c038c5f520dc83a35af848b1bbe8cc04a9826e4f9ce15a60 is 0
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 22.556 s <<< FAILURE! - in dev.jlibra.SimpleTransactionIT
[ERROR] transferTest(dev.jlibra.SimpleTransactionIT)  Time elapsed: 22.25 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in dev.jlibra.SimpleTransactionIT Account address: 37b7de33f04fefc1c038c5f520dc83a35af848b1bbe8cc04a9826e4f9ce15a60, expected balance: 1000, actual balance: 0 expected:<0> but was:<1000> within 20 seconds.
	at dev.jlibra.SimpleTransactionIT.transferTest(SimpleTransactionIT.java:114)
Caused by: java.lang.AssertionError: Account address: 37b7de33f04fefc1c038c5f520dc83a35af848b1bbe8cc04a9826e4f9ce15a60, expected balance: 1000, actual balance: 0 expected:<0> but was:<1000>
	at dev.jlibra.SimpleTransactionIT.lambda$transferTest$0(SimpleTransactionIT.java:118)
```

**Comment by straumat** [comment]
In my code, `getAdmissionControlStatus().getCode().getNumber()` is equal to `Accepted_VALUE` and `result.getVmStatus().getHasMessage()` is equal to `false` so I have no idea why the transaction is not really created

**Comment by ketola** [comment]
The account state data has changed, there's a new field that needs to be handled, see #53
