### ISSUE TITLE
UNAVAILABLE: HTTP/2 error code: NO_ERROR Received Goaway

### ISSUE THREAD

**Issue by bitcard** [ketola/jlibra#65]
I test it on android device, when send Libra, sometime fail with the follow error:

2019-11-13 16:09:36.052 2487-4755/test.app W/System.err: io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR
2019-11-13 16:09:36.053 2487-4755/test.app W/System.err: Received Goaway
2019-11-13 16:09:36.053 2487-4755/test.app W/System.err:     at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:230)
2019-11-13 16:09:36.053 2487-4755/test.app W/System.err:     at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:211)
2019-11-13 16:09:36.053 2487-4755/test.app W/System.err:     at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:144)
2019-11-13 16:09:36.054 2487-4755/test.app W/System.err:     at admission_control.AdmissionControlGrpc$AdmissionControlBlockingStub.submitTransaction(AdmissionControlGrpc.java:211)
2019-11-13 16:09:36.054 2487-4755/test.app W/System.err:     at dev.jlibra.admissioncontrol.AdmissionControl.submitTransaction(AdmissionControl.java:34)

thanks for your reply.

**Comment by bitcard** [comment]
but sometimes sent Libra is ok.

**Comment by ketola** [comment]
Sounds like a server / network problem. How often does this happen? I have been planning to test on android but have not had time to set up the dev environment for that.

**Comment by ketola** [comment]
I will go ahead and close this as there has not been any additional information to solve this. If you still have this issue and you are able to provide some more information I can re-open this.
